/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.artcomp.wiew;

import br.com.artcomp.cell.PintarCabecalho;
import br.com.artcomp.cell.TableActionCellEditor;
import br.com.artcomp.cell.TableActionCellRender;
import br.com.artcomp.cell.TableActionEvent;
import br.com.artcomp.controller.UpdateObjeto;
import br.com.artcomp.controller.VerificaSenha;
import br.com.artcomp.model.Objetos;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author artco
 */
public class TelaEditar extends javax.swing.JInternalFrame {

    String T = "";
    Integer id = 0;
    String imagem = "art";

    public TelaEditar() {
        initComponents();

        this.JTNome.setBackground(new Color(9, 73, 110));
        this.JTNome.setFont(new Font("Square721 BT", 1, 14));
        this.JTNome.setForeground(new Color(255, 255, 255));
        this.JTNome.setToolTipText("");
        this.JTNome.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255)));
        this.JTNome.setCaretColor(new Color(255, 255, 255));
        this.JTNome.setDisabledTextColor(new Color(255, 255, 255));
        this.JTNome.setOpaque(false);
        this.JTNome.setSelectionColor(new Color(9, 73, 110));

        this.JTSobNome.setBackground(new Color(9, 73, 110));
        this.JTSobNome.setFont(new Font("Square721 BT", 1, 14));
        this.JTSobNome.setForeground(new Color(255, 255, 255));
        this.JTSobNome.setToolTipText("");
        this.JTSobNome.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255)));
        this.JTSobNome.setCaretColor(new Color(255, 255, 255));
        this.JTSobNome.setDisabledTextColor(new Color(255, 255, 255));
        this.JTSobNome.setOpaque(false);
        this.JTSobNome.setSelectionColor(new Color(9, 73, 110));

        this.JTLogin.setBackground(new Color(9, 73, 110));
        this.JTLogin.setFont(new Font("Square721 BT", 1, 14));
        this.JTLogin.setForeground(new Color(255, 255, 255));
        this.JTLogin.setToolTipText("");
        this.JTLogin.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255)));
        this.JTLogin.setCaretColor(new Color(255, 255, 255));
        this.JTLogin.setDisabledTextColor(new Color(255, 255, 255));
        this.JTLogin.setOpaque(false);
        this.JTLogin.setSelectionColor(new Color(9, 73, 110));

        this.JTSenha.setBackground(new Color(9, 73, 110));
        this.JTSenha.setFont(new Font("Square721 BT", 1, 14));
        this.JTSenha.setForeground(new Color(255, 255, 255));
        this.JTSenha.setToolTipText("");
        this.JTSenha.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(255, 255, 255)));
        this.JTSenha.setCaretColor(new Color(255, 255, 255));
        this.JTSenha.setDisabledTextColor(new Color(255, 255, 255));
        this.JTSenha.setOpaque(false);
        this.JTSenha.setSelectionColor(new Color(9, 73, 110));

        this.setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
        this.kGradientPanel7.setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
        this.kGradientPanel2.setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
        this.kGradientPanel3.setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
        this.kGradientPanel4.setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
        this.kGradientPanel5.setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));
        this.kGradientPanel6.setBackground(new Color(0.0F, 0.0F, 0.0F, 0.0F));

        this.setSize(760, 595);
        this.setLocation(0, 0);

        kGradientPanel7.setSize(740, 530);

        kGradientPanel5.setVisible(false);

        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);// remove a barra do JInternoFrame
    }

    public void mostraDados(Integer ID, String nome, String palavraChave, String login, String senha) {
        id = ID;
        JTNome.setText(nome);
        JTSobNome.setText(palavraChave);
        JTLogin.setText(login);
        T = senha;
        JTSenha.setText("********");
        JTSenha.setEditable(false);
        System.out.println("o valor de senha  " + senha);

    }

    public void atualizaDados() {
        this.dispose();
        JTSenha.setVisible(false);
    }

    private void limpaDados() {
        JTNome.setText("");
        JTSobNome.setText("");
        JTLogin.setText("");
        JTSenha.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel7 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btolhar = new br.com.artcomp.cell.ActionButton();
        btolhar2 = new br.com.artcomp.cell.ActionButton();
        JTNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTSobNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kGradientPanel3 = new com.k33ptoo.components.KGradientPanel();
        JTLogin = new javax.swing.JTextField();
        kGradientPanel4 = new com.k33ptoo.components.KGradientPanel();
        JTSenha = new javax.swing.JTextField();
        btolhar1 = new br.com.artcomp.cell.ActionButton();
        jLabel1 = new javax.swing.JLabel();
        jBFechar = new javax.swing.JButton();
        kGradientPanel5 = new com.k33ptoo.components.KGradientPanel();
        kGradientPanel6 = new com.k33ptoo.components.KGradientPanel();
        JTSenha2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        kButton2 = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();
        btolhar3 = new br.com.artcomp.cell.ActionButton();
        jBFechar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 102, 0));
        setBorder(null);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(750, 590));

        kGradientPanel7.setkEndColor(new java.awt.Color(233, 93, 0));
        kGradientPanel7.setkGradientFocus(200);
        kGradientPanel7.setkStartColor(new java.awt.Color(233, 93, 0));
        kGradientPanel7.setkTransparentControls(false);

        kGradientPanel2.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel2.setkStartColor(new java.awt.Color(255, 102, 0));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login");
        kGradientPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, 30));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Senha");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, 30));

        btolhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/olho.png"))); // NOI18N
        btolhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btolharActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btolhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 40, 40));

        btolhar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/cadeado.png"))); // NOI18N
        btolhar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btolhar2ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btolhar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 40, 40));

        JTNome.setBackground(new java.awt.Color(30, 30, 30));
        JTNome.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        JTNome.setForeground(new java.awt.Color(255, 255, 255));
        JTNome.setToolTipText("");
        JTNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        JTNome.setCaretColor(new java.awt.Color(255, 255, 255));
        JTNome.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        JTNome.setSelectionColor(new java.awt.Color(9, 73, 110));
        kGradientPanel2.add(JTNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 360, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sobre Nome");
        kGradientPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 120, 20));

        JTSobNome.setBackground(new java.awt.Color(30, 30, 30));
        JTSobNome.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        JTSobNome.setForeground(new java.awt.Color(255, 255, 255));
        JTSobNome.setToolTipText("");
        JTSobNome.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        JTSobNome.setCaretColor(new java.awt.Color(255, 255, 255));
        JTSobNome.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        JTSobNome.setSelectionColor(new java.awt.Color(9, 73, 110));
        JTSobNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTSobNomeActionPerformed(evt);
            }
        });
        kGradientPanel2.add(JTSobNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 360, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        kGradientPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, 20));

        kGradientPanel3.setkBorderRadius(30);
        kGradientPanel3.setkEndColor(new java.awt.Color(170, 68, 0));
        kGradientPanel3.setkStartColor(new java.awt.Color(170, 68, 0));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTLogin.setBackground(new java.awt.Color(30, 30, 30));
        JTLogin.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        JTLogin.setForeground(new java.awt.Color(255, 255, 255));
        JTLogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTLogin.setToolTipText("");
        JTLogin.setBorder(null);
        JTLogin.setCaretColor(new java.awt.Color(255, 255, 255));
        JTLogin.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        JTLogin.setSelectionColor(new java.awt.Color(9, 73, 110));
        kGradientPanel3.add(JTLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        kGradientPanel2.add(kGradientPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 300, 38));

        kGradientPanel4.setkBorderRadius(30);
        kGradientPanel4.setkEndColor(new java.awt.Color(170, 68, 0));
        kGradientPanel4.setkStartColor(new java.awt.Color(170, 68, 0));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTSenha.setBackground(new java.awt.Color(30, 30, 30));
        JTSenha.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        JTSenha.setForeground(new java.awt.Color(255, 255, 255));
        JTSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTSenha.setText("***************");
        JTSenha.setToolTipText("");
        JTSenha.setBorder(null);
        JTSenha.setCaretColor(new java.awt.Color(255, 255, 255));
        JTSenha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        JTSenha.setSelectionColor(new java.awt.Color(9, 73, 110));
        kGradientPanel4.add(JTSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 40));

        kGradientPanel2.add(kGradientPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 300, 38));

        btolhar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/Itens.png"))); // NOI18N
        btolhar1.setFocusable(false);
        btolhar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btolhar1ActionPerformed(evt);
            }
        });
        kGradientPanel2.add(btolhar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/camera.png"))); // NOI18N
        kGradientPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, 100));

        jBFechar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBFechar.setForeground(new java.awt.Color(255, 255, 255));
        jBFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/seta.png"))); // NOI18N
        jBFechar.setToolTipText("FECHAR");
        jBFechar.setBorder(null);
        jBFechar.setBorderPainted(false);
        jBFechar.setContentAreaFilled(false);
        jBFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFechar.setFocusPainted(false);
        jBFechar.setFocusable(false);
        jBFechar.setRolloverEnabled(false);
        jBFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFecharActionPerformed(evt);
            }
        });
        kGradientPanel2.add(jBFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        kGradientPanel5.setkEndColor(new java.awt.Color(255, 102, 0));
        kGradientPanel5.setkStartColor(new java.awt.Color(255, 102, 0));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel6.setkBorderRadius(30);
        kGradientPanel6.setkEndColor(new java.awt.Color(170, 68, 0));
        kGradientPanel6.setkStartColor(new java.awt.Color(170, 68, 0));
        kGradientPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JTSenha2.setBackground(new java.awt.Color(170, 68, 0));
        JTSenha2.setFont(new java.awt.Font("Square721 BT", 1, 14)); // NOI18N
        JTSenha2.setForeground(new java.awt.Color(255, 255, 255));
        JTSenha2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JTSenha2.setToolTipText("");
        JTSenha2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        JTSenha2.setCaretColor(new java.awt.Color(255, 255, 255));
        JTSenha2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        JTSenha2.setSelectionColor(new java.awt.Color(9, 73, 110));
        JTSenha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTSenha2KeyPressed(evt);
            }
        });
        kGradientPanel6.add(JTSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 330, 40));

        kGradientPanel5.add(kGradientPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 228, 360, 40));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Digite sua senha ! ");
        kGradientPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 183, 350, 40));

        kButton2.setText("Descriptografar");
        kButton2.setBorderPainted(false);
        kButton2.setFocusPainted(false);
        kButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        kButton2.setkBackGroundColor(new java.awt.Color(0, 255, 255));
        kButton2.setkBorderRadius(20);
        kButton2.setkEndColor(new java.awt.Color(255, 255, 255));
        kButton2.setkFillButton(false);
        kButton2.setkHoverColor(new java.awt.Color(255, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 102, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 102, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        kButton2.setkIndicatorColor(new java.awt.Color(0, 255, 255));
        kButton2.setkPressedColor(new java.awt.Color(255, 255, 255));
        kButton2.setkStartColor(new java.awt.Color(255, 102, 0));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel5.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 286, 300, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/camera.png"))); // NOI18N
        kGradientPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, 100));

        btolhar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/Itens.png"))); // NOI18N
        btolhar3.setFocusable(false);
        btolhar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btolhar3ActionPerformed(evt);
            }
        });
        kGradientPanel5.add(btolhar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 40, -1));

        jBFechar1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jBFechar1.setForeground(new java.awt.Color(255, 255, 255));
        jBFechar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/seta.png"))); // NOI18N
        jBFechar1.setToolTipText("FECHAR");
        jBFechar1.setBorder(null);
        jBFechar1.setBorderPainted(false);
        jBFechar1.setContentAreaFilled(false);
        jBFechar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBFechar1.setFocusPainted(false);
        jBFechar1.setFocusable(false);
        jBFechar1.setRolloverEnabled(false);
        jBFechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFechar1ActionPerformed(evt);
            }
        });
        kGradientPanel5.add(jBFechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        javax.swing.GroupLayout kGradientPanel7Layout = new javax.swing.GroupLayout(kGradientPanel7);
        kGradientPanel7.setLayout(kGradientPanel7Layout);
        kGradientPanel7Layout.setHorizontalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
            .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        kGradientPanel7Layout.setVerticalGroup(
            kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
            .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(kGradientPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(kGradientPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(kGradientPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        setBounds(0, 0, 750, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void btolharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btolharActionPerformed

        kGradientPanel2.setVisible(false);
        kGradientPanel5.setVisible(true);
        JTSenha2.requestFocus();
    }//GEN-LAST:event_btolharActionPerformed

    private void btolhar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btolhar2ActionPerformed

        UpdateObjeto up = new UpdateObjeto();

        if (up.updateObjeto(id, JTLogin.getText(), JTSenha.getText(), JTNome.getText(), JTSobNome.getText(), imagem)) {

            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso ");
            //instancia de uma classe fabrica
            TelaTabela tab = new TelaTabela();
            getParent().add(tab);
            tab.setVisible(true);
            limpaDados();
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Erro de Gravação ");
        }
    }//GEN-LAST:event_btolhar2ActionPerformed

    private void JTSobNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTSobNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTSobNomeActionPerformed

    private void btolhar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btolhar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btolhar1ActionPerformed

    private void jBFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFecharActionPerformed

        TelaTabela tab = new TelaTabela();
        getParent().add(tab);
        tab.setVisible(true);
        limpaDados();
        this.dispose();
    }//GEN-LAST:event_jBFecharActionPerformed

    private void JTSenha2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTSenha2KeyPressed

        if (evt.getKeyCode() == evt.VK_ENTER) {

            VerificaSenha vs = new VerificaSenha();
            if (vs.VerificaSenha(JTSenha2.getText())) {

                JTSenha.setText(T);
                kGradientPanel2.setVisible(false);
                kGradientPanel7.setVisible(true);
            } else {
                System.out.println("erro da senha");
            }

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_JTSenha2KeyPressed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed

        VerificaSenha vs = new VerificaSenha();
        if (vs.VerificaSenha(JTSenha2.getText())) {

            JTSenha.setText(T);
            kGradientPanel5.setVisible(false);
            kGradientPanel2.setVisible(true);
            btolhar.setVisible(false);
            btolhar2.setVisible(true);
        } else {
            System.out.println("erro da senha");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_kButton2ActionPerformed

    private void btolhar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btolhar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btolhar3ActionPerformed

    private void jBFechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFechar1ActionPerformed
        TelaTabela tab = new TelaTabela();
        getParent().add(tab);
        tab.setVisible(true);
        limpaDados();
        this.dispose();
    }//GEN-LAST:event_jBFechar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTLogin;
    private javax.swing.JTextField JTNome;
    private javax.swing.JTextField JTSenha;
    private javax.swing.JTextField JTSenha2;
    private javax.swing.JTextField JTSobNome;
    private br.com.artcomp.cell.ActionButton btolhar;
    private br.com.artcomp.cell.ActionButton btolhar1;
    private br.com.artcomp.cell.ActionButton btolhar2;
    private br.com.artcomp.cell.ActionButton btolhar3;
    private javax.swing.JButton jBFechar;
    private javax.swing.JButton jBFechar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private com.k33ptoo.components.KButton kButton2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private com.k33ptoo.components.KGradientPanel kGradientPanel3;
    private com.k33ptoo.components.KGradientPanel kGradientPanel4;
    private com.k33ptoo.components.KGradientPanel kGradientPanel5;
    private com.k33ptoo.components.KGradientPanel kGradientPanel6;
    public com.k33ptoo.components.KGradientPanel kGradientPanel7;
    // End of variables declaration//GEN-END:variables
}
