package br.com.artcomp.cell;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
    }

    public void initEvent(TableActionEvent event, int row) {
        bteditar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onEdit(row);
            }
        });
//       artur  artcomp

        btolhar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onView(row);
            }
        });
        
        btolhar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bteditar = new br.com.artcomp.cell.ActionButton();
        btolhar = new br.com.artcomp.cell.ActionButton();
        bteditar1 = new br.com.artcomp.cell.ActionButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bteditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/lapis.png"))); // NOI18N
        bteditar.setFocusable(false);
        bteditar.setRequestFocusEnabled(false);
        add(bteditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 40));

        btolhar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/olho.png"))); // NOI18N
        btolhar.setFocusable(false);
        add(btolhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 40, 40));

        bteditar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/artcomp/imagens/lixeira.png"))); // NOI18N
        bteditar1.setFocusable(false);
        bteditar1.setRequestFocusEnabled(false);
        add(bteditar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 40, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.com.artcomp.cell.ActionButton bteditar;
    private br.com.artcomp.cell.ActionButton bteditar1;
    private br.com.artcomp.cell.ActionButton btolhar;
    // End of variables declaration//GEN-END:variables

}
